[package]
name = "sshx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
nix = "0.23.1"
pin-project = "1.0.10"
sshx-core = { path = "../sshx-core" }
tokio = { version = "1.18.1", features = ["full"] }
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
