[package]
name = "sshx"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
close_fds = "0.3.2"
encoding_rs = "0.8.31"
nix = "0.23.1"
pin-project = "1.0.10"
sshx-core = { path = "../sshx-core" }
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.9"
tonic = { version = "0.8.0", features = ["tls", "tls-roots"] }
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
