[package]
name = "sshx-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
async-channel = "1.6.1"
async-stream = "0.3.3"
axum = { version = "0.5.7", features = ["ws"] }
base64 = "0.13.0"
ciborium = "0.2.0"
clap = { version = "3.1.6", features = ["derive"] }
dashmap = "5.2.0"
hmac = "0.12.1"
hyper = { version = "0.14.18", features = ["full"] }
nanoid = "0.4.0"
parking_lot = "0.12.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_bytes = "0.11.6"
sha2 = "0.10.2"
sshx-core = { path = "../sshx-core" }
tokio = { version = "1.18.1", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["sync"] }
tonic = { version = "0.7.2", features = ["tls", "tls-roots"] }
tonic-reflection = "0.4.0"
tower = { version = "0.4.12", features = ["steer"] }
tower-http = { version = "0.3.2", features = ["fs", "redirect", "trace"] }
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[dev-dependencies]
futures-util = { version = "0.3.23", features = ["sink"] }
reqwest = "0.11.10"
sshx = { path = "../sshx" }
tokio-tungstenite = "0.17.2"
