[package]
name = "sshx-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
sshx-core = { path = "../sshx-core" }
tokio = { version = "1.16.1", features = ["full"] }
tonic = "0.6.2"
tonic-reflection = "0.3.0"
