[package]
name = "sshx-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
axum = "0.4.5"
clap = { version = "3.1.6", features = ["derive"] }
hyper = { version = "0.14.17", features = ["full"] }
sshx-core = { path = "../sshx-core" }
tokio = { version = "1.16.1", features = ["full"] }
tokio-stream = "0.1.8"
tonic = { version = "0.6.2", features = ["tls", "tls-roots"] }
tonic-reflection = "0.3.0"
tower = { version = "0.4.11", features = ["steer"] }
tower-http = { version = "0.2.2", features = ["fs", "trace"] }
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[features]
