[package]
name = "sshx-core"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.9.0"
tonic = { version = "0.6.2", features = ["tls", "tls-roots"] }

[build-dependencies]
tonic-build = "0.6.2"
