[package]
name = "sshx-core"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.10.3"
tonic = { version = "0.7.2", features = ["tls", "tls-roots"] }

[build-dependencies]
tonic-build = "0.7.2"
