name: CI

on: [push, pull_request]

jobs:
  rustfmt:
    name: Rust format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - run: cargo fmt -- --check

  rust:
    name: Rust lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo clippy --all-targets -- -D warnings

      - run: cargo test
